/**
 * DEMO DATA — synthetic lab data used until the SentinelIQ FastAPI backend is connected.
 * Every value here is fabricated for UI demonstration only. No real hosts, users or
 * measured performance figures. All screens surface a "DEMO DATA" marker while this
 * dataset is in use.
 */
import type {
  AnalyticsMetrics,
  CorrelationGroup,
  DashboardMetrics,
  HealthResponse,
  Incident,
  IncidentExplanation,
  MitreTechnique,
  WazuhAlert,
} from "./types";

const DAY = "2026-08-09";
const t = (hhmmss: string) => `${DAY}T${hhmmss}Z`;

function raw(a: Partial<WazuhAlert> & { rule_id: string; rule_level: number }) {
  return {
    timestamp: a.timestamp,
    agent: { id: "003", name: a.agent, ip: "192.168.1.40" },
    rule: {
      id: a.rule_id,
      level: a.rule_level,
      description: a.rule_description,
      groups: ["authentication", "syslog"],
      mitre: { id: ["T1078"], tactic: ["Defense Evasion"] },
    },
    data: {
      srcip: a.source_ip,
      dstuser: a.username,
      srcport: "48212",
    },
    decoder: { name: "sshd" },
    location: "/var/log/auth.log",
    full_log: `${a.rule_description} from ${a.source_ip}`,
  } as Record<string, unknown>;
}

function alert(a: Omit<WazuhAlert, "raw">): WazuhAlert {
  return { ...a, raw: raw(a) };
}

export const demoAlerts: WazuhAlert[] = [
  // INC-2026-0042 — SSH brute force to successful login chain
  alert({
    id: "ALT-100241",
    timestamp: t("10:32:14"),
    rule_id: "5716",
    rule_description: "sshd: Failed SSH authentication for invalid user",
    rule_level: 5,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "backupsvc",
    event_type: "authentication_failure",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100242",
    timestamp: t("10:32:20"),
    rule_id: "5720",
    rule_description: "sshd: Multiple authentication failures from same source",
    rule_level: 6,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "backupsvc",
    event_type: "authentication_failure",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100243",
    timestamp: t("10:32:41"),
    rule_id: "5720",
    rule_description: "sshd: Brute force attempt pattern detected",
    rule_level: 7,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "authentication_failure",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100244",
    timestamp: t("10:33:02"),
    rule_id: "5715",
    rule_description: "sshd: Successful authentication after repeated failures",
    rule_level: 10,
    severity: "high",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "authentication_success",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100245",
    timestamp: t("10:33:40"),
    rule_id: "92213",
    rule_description: "Suspicious command execution in user session",
    rule_level: 11,
    severity: "high",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "process_execution",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100246",
    timestamp: t("10:34:05"),
    rule_id: "554",
    rule_description: "File added to monitored directory (/tmp)",
    rule_level: 7,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "file_activity",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100247",
    timestamp: t("10:34:31"),
    rule_id: "2902",
    rule_description: "New group/user membership modification detected",
    rule_level: 8,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "privilege_change",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),
  alert({
    id: "ALT-100248",
    timestamp: t("10:35:02"),
    rule_id: "5402",
    rule_description: "Successful sudo to root",
    rule_level: 9,
    severity: "high",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "privilege_change",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0042",
  }),

  // INC-2026-0043 — PowerShell activity on Windows workstation
  alert({
    id: "ALT-100260",
    timestamp: t("11:04:11"),
    rule_id: "91802",
    rule_description: "Windows PowerShell: encoded command line detected",
    rule_level: 12,
    severity: "critical",
    agent: "agent-005",
    host: "win-workstation-02",
    source_ip: "192.168.1.31",
    destination_ip: "192.168.1.52",
    username: "labuser",
    event_type: "process_execution",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0043",
  }),
  alert({
    id: "ALT-100261",
    timestamp: t("11:04:48"),
    rule_id: "92052",
    rule_description: "PowerShell downloaded content from remote host",
    rule_level: 11,
    severity: "high",
    agent: "agent-005",
    host: "win-workstation-02",
    source_ip: "192.168.1.31",
    destination_ip: "192.168.1.52",
    username: "labuser",
    event_type: "network_connection",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0043",
  }),
  alert({
    id: "ALT-100262",
    timestamp: t("11:05:20"),
    rule_id: "92214",
    rule_description: "Scheduled task created by non-admin process",
    rule_level: 10,
    severity: "high",
    agent: "agent-005",
    host: "win-workstation-02",
    source_ip: "192.168.1.31",
    destination_ip: "192.168.1.52",
    username: "labuser",
    event_type: "persistence",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0043",
  }),
  alert({
    id: "ALT-100263",
    timestamp: t("11:06:02"),
    rule_id: "554",
    rule_description: "Executable file created in user AppData directory",
    rule_level: 8,
    severity: "medium",
    agent: "agent-005",
    host: "win-workstation-02",
    source_ip: "192.168.1.31",
    destination_ip: "192.168.1.52",
    username: "labuser",
    event_type: "file_activity",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0043",
  }),

  // INC-2026-0044 — web server scanning
  alert({
    id: "ALT-100270",
    timestamp: t("09:12:03"),
    rule_id: "31103",
    rule_description: "Web server 400 error codes burst (possible scan)",
    rule_level: 6,
    severity: "medium",
    agent: "agent-004",
    host: "web-node-01",
    source_ip: "10.10.20.77",
    destination_ip: "192.168.1.60",
    username: null,
    event_type: "web_scan",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0044",
  }),
  alert({
    id: "ALT-100271",
    timestamp: t("09:12:44"),
    rule_id: "31151",
    rule_description: "Multiple web authentication failures",
    rule_level: 7,
    severity: "medium",
    agent: "agent-004",
    host: "web-node-01",
    source_ip: "10.10.20.77",
    destination_ip: "192.168.1.60",
    username: "admin",
    event_type: "authentication_failure",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0044",
  }),
  alert({
    id: "ALT-100272",
    timestamp: t("09:13:19"),
    rule_id: "31106",
    rule_description: "Common web attack pattern in URL",
    rule_level: 9,
    severity: "high",
    agent: "agent-004",
    host: "web-node-01",
    source_ip: "10.10.20.77",
    destination_ip: "192.168.1.60",
    username: null,
    event_type: "web_attack",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0044",
  }),

  // INC-2026-0045 — database off-hours access
  alert({
    id: "ALT-100280",
    timestamp: t("02:41:08"),
    rule_id: "5501",
    rule_description: "PAM: login session opened outside business hours",
    rule_level: 5,
    severity: "low",
    agent: "agent-006",
    host: "db-node-01",
    source_ip: "192.168.1.18",
    destination_ip: "192.168.1.70",
    username: "dbops",
    event_type: "authentication_success",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0045",
  }),
  alert({
    id: "ALT-100281",
    timestamp: t("02:44:52"),
    rule_id: "92216",
    rule_description: "Large database export executed",
    rule_level: 9,
    severity: "high",
    agent: "agent-006",
    host: "db-node-01",
    source_ip: "192.168.1.18",
    destination_ip: "192.168.1.70",
    username: "dbops",
    event_type: "data_access",
    correlation_status: "part_of_incident",
    incident_id: "INC-2026-0045",
  }),

  // Uncorrelated / standalone alerts
  alert({
    id: "ALT-100290",
    timestamp: t("08:02:19"),
    rule_id: "5501",
    rule_description: "PAM: login session opened",
    rule_level: 3,
    severity: "low",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: "192.168.1.12",
    destination_ip: "192.168.1.40",
    username: "operator",
    event_type: "authentication_success",
    correlation_status: "uncorrelated",
    incident_id: null,
  }),
  alert({
    id: "ALT-100291",
    timestamp: t("08:47:55"),
    rule_id: "2501",
    rule_description: "Syslog: service restarted",
    rule_level: 4,
    severity: "low",
    agent: "agent-004",
    host: "web-node-01",
    source_ip: null,
    destination_ip: null,
    username: null,
    event_type: "system",
    correlation_status: "uncorrelated",
    incident_id: null,
  }),
  alert({
    id: "ALT-100292",
    timestamp: t("09:58:31"),
    rule_id: "5716",
    rule_description: "sshd: Failed SSH authentication",
    rule_level: 5,
    severity: "medium",
    agent: "agent-006",
    host: "db-node-01",
    source_ip: "192.168.1.44",
    destination_ip: "192.168.1.70",
    username: "root",
    event_type: "authentication_failure",
    correlation_status: "correlated",
    incident_id: null,
  }),
  alert({
    id: "ALT-100293",
    timestamp: t("10:11:07"),
    rule_id: "533",
    rule_description: "Listened ports status changed",
    rule_level: 7,
    severity: "medium",
    agent: "agent-005",
    host: "win-workstation-02",
    source_ip: null,
    destination_ip: null,
    username: null,
    event_type: "system",
    correlation_status: "uncorrelated",
    incident_id: null,
  }),
  alert({
    id: "ALT-100294",
    timestamp: t("07:22:40"),
    rule_id: "510",
    rule_description: "Integrity checksum changed on monitored file",
    rule_level: 7,
    severity: "medium",
    agent: "agent-003",
    host: "ubuntu-server",
    source_ip: null,
    destination_ip: null,
    username: "root",
    event_type: "file_activity",
    correlation_status: "correlated",
    incident_id: null,
  }),
];

export const demoIncidents: Incident[] = [
  {
    id: "INC-2026-0042",
    ai_abstained: false,
    prediction_set: "High",
    title: "Suspicious Authentication Activity",
    severity: "high",
    status: "investigating",
    priority_score: 87,
    ml_prediction: "high",
    alert_count: 8,
    first_seen: t("10:32:14"),
    last_seen: t("10:35:02"),
    host: "ubuntu-server",
    source_ip: "192.168.1.25",
    mitre_techniques: ["T1110", "T1078", "T1059"],
    assigned_analyst: "analyst.rk",
    correlation_group: "CG-001",
    summary: {
      text: "Multiple authentication failures from the same source were followed by a successful login and subsequent suspicious command execution on the affected host. The correlated activity requires analyst investigation.",
      provider: "Ollama / Local LLM",
      model: "llama3.1:8b",
      generated_at: t("10:36:12"),
    },
    notes: [
      {
        id: "NOTE-1",
        author: "analyst.rk",
        created_at: t("10:41:02"),
        body: "Confirmed the source address is not part of the approved admin jump-host range for this lab segment. Continuing host-side review of the executed commands.",
      },
    ],
  },
  {
    id: "INC-2026-0043",
    ai_abstained: false,
    prediction_set: "Critical",
    title: "Encoded PowerShell Execution With Persistence Attempt",
    severity: "critical",
    status: "escalated",
    priority_score: 94,
    ml_prediction: "critical",
    alert_count: 4,
    first_seen: t("11:04:11"),
    last_seen: t("11:06:02"),
    host: "win-workstation-02",
    source_ip: "192.168.1.31",
    mitre_techniques: ["T1059", "T1053"],
    assigned_analyst: "analyst.mv",
    correlation_group: "CG-002",
    summary: {
      text: "An encoded PowerShell command line was observed on the workstation, followed by remote content retrieval, creation of a scheduled task and an executable written to a user directory. The grouped alerts indicate follow-on activity after initial execution and require analyst review.",
      provider: "Ollama / Local LLM",
      model: "llama3.1:8b",
      generated_at: t("11:07:40"),
    },
    notes: [],
  },
  {
    id: "INC-2026-0044",
    ai_abstained: true,
    prediction_set: "Medium, High",
    title: "Web Scanning Followed By Attack Pattern",
    severity: "medium",
    status: "triaged",
    priority_score: 61,
    ml_prediction: "medium",
    alert_count: 3,
    first_seen: t("09:12:03"),
    last_seen: t("09:13:19"),
    host: "web-node-01",
    source_ip: "10.10.20.77",
    mitre_techniques: ["T1595", "T1110"],
    assigned_analyst: null,
    correlation_group: "CG-003",
    summary: {
      text: "A burst of web server error responses from a single external address was followed by repeated web authentication failures and a request containing a known attack pattern. No successful authentication was recorded in the correlated alert set.",
      provider: "Ollama / Local LLM",
      model: "llama3.1:8b",
      generated_at: t("09:15:02"),
    },
    notes: [],
  },
  {
    id: "INC-2026-0045",
    ai_abstained: true,
    prediction_set: "Medium, High, Critical",
    title: "Off-Hours Database Access With Large Export",
    severity: "high",
    status: "new",
    priority_score: 78,
    ml_prediction: "high",
    alert_count: 2,
    first_seen: t("02:41:08"),
    last_seen: t("02:44:52"),
    host: "db-node-01",
    source_ip: "192.168.1.18",
    mitre_techniques: ["T1078"],
    assigned_analyst: null,
    correlation_group: "CG-004",
    summary: {
      text: "A session was opened on the database host outside configured business hours and a large export operation was executed shortly afterwards. The two alerts were grouped on shared host, account and time proximity.",
      provider: "Ollama / Local LLM",
      model: "llama3.1:8b",
      generated_at: t("02:47:10"),
    },
    notes: [],
  },
];

export const demoExplanations: Record<string, IncidentExplanation> = {
  "INC-2026-0042": {
    model: "XGBoost",
    model_version: "sentineliq-triage-v0.4",
    prediction: "high",
    priority_score: 87,
    base_value: 0.42,
    features: [
      { key: "alert_count", label: "Alert count", value: 8 },
      { key: "max_alert_severity", label: "Maximum alert severity", value: "high (level 11)" },
      { key: "auth_failures", label: "Authentication failures", value: 3 },
      { key: "suspicious_process_activity", label: "Suspicious process activity", value: 1 },
      { key: "privilege_changes", label: "Privilege changes", value: 2 },
      { key: "affected_hosts", label: "Number of affected hosts", value: 1 },
      { key: "event_frequency", label: "Event frequency (alerts/min)", value: 2.8 },
      { key: "time_window_minutes", label: "Time-window span (minutes)", value: 2.8 },
    ],
    shap_values: [
      { feature: "max_alert_severity", label: "Maximum alert severity", contribution: 0.31 },
      { feature: "suspicious_process_activity", label: "Suspicious process activity", contribution: 0.24 },
      { feature: "auth_failures", label: "Authentication failures", contribution: 0.18 },
      { feature: "privilege_changes", label: "Privilege change", contribution: 0.12 },
      { feature: "event_frequency", label: "Alert frequency", contribution: 0.08 },
      { feature: "affected_hosts", label: "Number of affected hosts", contribution: -0.05 },
    ],
  },
  "INC-2026-0043": {
    model: "XGBoost",
    model_version: "sentineliq-triage-v0.4",
    prediction: "critical",
    priority_score: 94,
    base_value: 0.42,
    features: [
      { key: "alert_count", label: "Alert count", value: 4 },
      { key: "max_alert_severity", label: "Maximum alert severity", value: "critical (level 12)" },
      { key: "auth_failures", label: "Authentication failures", value: 0 },
      { key: "suspicious_process_activity", label: "Suspicious process activity", value: 2 },
      { key: "privilege_changes", label: "Privilege changes", value: 0 },
      { key: "affected_hosts", label: "Number of affected hosts", value: 1 },
      { key: "event_frequency", label: "Event frequency (alerts/min)", value: 2.1 },
      { key: "time_window_minutes", label: "Time-window span (minutes)", value: 1.9 },
    ],
    shap_values: [
      { feature: "max_alert_severity", label: "Maximum alert severity", contribution: 0.36 },
      { feature: "suspicious_process_activity", label: "Suspicious process activity", contribution: 0.29 },
      { feature: "persistence_indicators", label: "Persistence indicators", contribution: 0.17 },
      { feature: "event_frequency", label: "Alert frequency", contribution: 0.06 },
      { feature: "auth_failures", label: "Authentication failures", contribution: -0.08 },
    ],
  },
  "INC-2026-0044": {
    model: "XGBoost",
    model_version: "sentineliq-triage-v0.4",
    prediction: "medium",
    priority_score: 61,
    base_value: 0.42,
    features: [
      { key: "alert_count", label: "Alert count", value: 3 },
      { key: "max_alert_severity", label: "Maximum alert severity", value: "high (level 9)" },
      { key: "auth_failures", label: "Authentication failures", value: 1 },
      { key: "suspicious_process_activity", label: "Suspicious process activity", value: 0 },
      { key: "privilege_changes", label: "Privilege changes", value: 0 },
      { key: "affected_hosts", label: "Number of affected hosts", value: 1 },
      { key: "event_frequency", label: "Event frequency (alerts/min)", value: 2.4 },
      { key: "time_window_minutes", label: "Time-window span (minutes)", value: 1.3 },
    ],
    shap_values: [
      { feature: "max_alert_severity", label: "Maximum alert severity", contribution: 0.19 },
      { feature: "auth_failures", label: "Authentication failures", contribution: 0.11 },
      { feature: "external_source", label: "External source address", contribution: 0.09 },
      { feature: "suspicious_process_activity", label: "Suspicious process activity", contribution: -0.14 },
      { feature: "privilege_changes", label: "Privilege change", contribution: -0.1 },
    ],
  },
  "INC-2026-0045": {
    model: "XGBoost",
    model_version: "sentineliq-triage-v0.4",
    prediction: "high",
    priority_score: 78,
    base_value: 0.42,
    features: [
      { key: "alert_count", label: "Alert count", value: 2 },
      { key: "max_alert_severity", label: "Maximum alert severity", value: "high (level 9)" },
      { key: "auth_failures", label: "Authentication failures", value: 0 },
      { key: "suspicious_process_activity", label: "Suspicious process activity", value: 0 },
      { key: "privilege_changes", label: "Privilege changes", value: 0 },
      { key: "affected_hosts", label: "Number of affected hosts", value: 1 },
      { key: "event_frequency", label: "Event frequency (alerts/min)", value: 0.5 },
      { key: "time_window_minutes", label: "Time-window span (minutes)", value: 3.7 },
    ],
    shap_values: [
      { feature: "off_hours_activity", label: "Off-hours activity", contribution: 0.27 },
      { feature: "data_volume", label: "Exported data volume", contribution: 0.22 },
      { feature: "max_alert_severity", label: "Maximum alert severity", contribution: 0.14 },
      { feature: "alert_count", label: "Alert count", contribution: -0.09 },
    ],
  },
};

export const demoMitre: Record<string, MitreTechnique[]> = {
  "INC-2026-0042": [
    {
      technique_id: "T1110",
      name: "Brute Force",
      tactic: "Credential Access",
      evidence: "3 authentication failures from 192.168.1.25 within 30 seconds (rules 5716, 5720)",
      confidence: 0.86,
    },
    {
      technique_id: "T1078",
      name: "Valid Accounts",
      tactic: "Defense Evasion",
      evidence: "Successful authentication for 'operator' immediately after failure burst (rule 5715)",
      confidence: 0.74,
    },
    {
      technique_id: "T1059",
      name: "Command and Scripting Interpreter",
      tactic: "Execution",
      evidence: "Suspicious command execution in the established session (rule 92213)",
      confidence: 0.69,
    },
  ],
  "INC-2026-0043": [
    {
      technique_id: "T1059",
      name: "Command and Scripting Interpreter",
      tactic: "Execution",
      evidence: "Encoded PowerShell command line observed (rule 91802)",
      confidence: 0.91,
    },
    {
      technique_id: "T1053",
      name: "Scheduled Task/Job",
      tactic: "Persistence",
      evidence: "Scheduled task created by a non-administrative process (rule 92214)",
      confidence: 0.72,
    },
  ],
  "INC-2026-0044": [
    {
      technique_id: "T1595",
      name: "Active Scanning",
      tactic: "Reconnaissance",
      evidence: "Burst of 400-class responses from a single external address (rule 31103)",
      confidence: 0.65,
    },
    {
      technique_id: "T1110",
      name: "Brute Force",
      tactic: "Credential Access",
      evidence: "Repeated web authentication failures for 'admin' (rule 31151)",
      confidence: 0.58,
    },
  ],
  "INC-2026-0045": [
    {
      technique_id: "T1078",
      name: "Valid Accounts",
      tactic: "Defense Evasion",
      evidence: "Valid 'dbops' session opened outside business hours (rule 5501)",
      confidence: 0.61,
    },
  ],
};

export const demoCorrelationGroups: CorrelationGroup[] = [
  {
    id: "CG-001",
    incident_id: "INC-2026-0042",
    alert_count: 8,
    window_minutes: 5,
    first_seen: t("10:32:14"),
    last_seen: t("10:35:02"),
    hosts: ["ubuntu-server"],
    source_ips: ["192.168.1.25"],
    reasons: [
      { label: "Same source IP", detail: "All 8 alerts originate from 192.168.1.25." },
      { label: "Same destination host", detail: "All alerts belong to agent-003 / ubuntu-server." },
      { label: "5-minute time window", detail: "First and last alert are 2m 48s apart." },
      { label: "Related event types", detail: "authentication_failure → authentication_success → process_execution → file_activity → privilege_change." },
      { label: "Shared account", detail: "Successful login and later activity use the same account 'operator'." },
    ],
    chain: [
      { stage: "Source", event_type: "source_ip", alert_ids: [], at: t("10:32:14") },
      { stage: "Authentication failures", event_type: "authentication_failure", alert_ids: ["ALT-100241", "ALT-100242", "ALT-100243"], at: t("10:32:14") },
      { stage: "Successful login", event_type: "authentication_success", alert_ids: ["ALT-100244"], at: t("10:33:02") },
      { stage: "Command execution", event_type: "process_execution", alert_ids: ["ALT-100245"], at: t("10:33:40") },
      { stage: "File activity", event_type: "file_activity", alert_ids: ["ALT-100246"], at: t("10:34:05") },
      { stage: "Privilege change", event_type: "privilege_change", alert_ids: ["ALT-100247", "ALT-100248"], at: t("10:34:31") },
    ],
  },
  {
    id: "CG-002",
    incident_id: "INC-2026-0043",
    alert_count: 4,
    window_minutes: 5,
    first_seen: t("11:04:11"),
    last_seen: t("11:06:02"),
    hosts: ["win-workstation-02"],
    source_ips: ["192.168.1.31"],
    reasons: [
      { label: "Same host", detail: "All alerts reported by agent-005 / win-workstation-02." },
      { label: "Same user session", detail: "All alerts reference account 'labuser'." },
      { label: "2-minute time window", detail: "Alerts span 1m 51s." },
      { label: "Execution → persistence sequence", detail: "process_execution → network_connection → persistence → file_activity." },
    ],
    chain: [
      { stage: "Encoded execution", event_type: "process_execution", alert_ids: ["ALT-100260"], at: t("11:04:11") },
      { stage: "Remote content retrieval", event_type: "network_connection", alert_ids: ["ALT-100261"], at: t("11:04:48") },
      { stage: "Persistence created", event_type: "persistence", alert_ids: ["ALT-100262"], at: t("11:05:20") },
      { stage: "File written", event_type: "file_activity", alert_ids: ["ALT-100263"], at: t("11:06:02") },
    ],
  },
  {
    id: "CG-003",
    incident_id: "INC-2026-0044",
    alert_count: 3,
    window_minutes: 5,
    first_seen: t("09:12:03"),
    last_seen: t("09:13:19"),
    hosts: ["web-node-01"],
    source_ips: ["10.10.20.77"],
    reasons: [
      { label: "Same source IP", detail: "All alerts originate from 10.10.20.77." },
      { label: "Same host", detail: "All alerts reported by agent-004 / web-node-01." },
      { label: "76-second window", detail: "Alerts fall inside the 5-minute correlation window." },
      { label: "Related event types", detail: "web_scan → authentication_failure → web_attack." },
    ],
    chain: [
      { stage: "Scanning", event_type: "web_scan", alert_ids: ["ALT-100270"], at: t("09:12:03") },
      { stage: "Credential attempts", event_type: "authentication_failure", alert_ids: ["ALT-100271"], at: t("09:12:44") },
      { stage: "Attack pattern", event_type: "web_attack", alert_ids: ["ALT-100272"], at: t("09:13:19") },
    ],
  },
  {
    id: "CG-004",
    incident_id: "INC-2026-0045",
    alert_count: 2,
    window_minutes: 5,
    first_seen: t("02:41:08"),
    last_seen: t("02:44:52"),
    hosts: ["db-node-01"],
    source_ips: ["192.168.1.18"],
    reasons: [
      { label: "Same host and account", detail: "Both alerts reference db-node-01 and account 'dbops'." },
      { label: "3m 44s window", detail: "Session open followed shortly by export operation." },
      { label: "Related event types", detail: "authentication_success → data_access." },
    ],
    chain: [
      { stage: "Session opened", event_type: "authentication_success", alert_ids: ["ALT-100280"], at: t("02:41:08") },
      { stage: "Data export", event_type: "data_access", alert_ids: ["ALT-100281"], at: t("02:44:52") },
    ],
  },
];

export const demoMetrics: DashboardMetrics = {
  critical_incidents: 1,
  high_incidents: 2,
  open_incidents: 4,
  alerts_today: demoAlerts.length,
  correlated_incidents: 4,
  avg_triage_minutes: 14,
  alerts_over_time: [
    { bucket: "00:00", alerts: 2, incidents: 0 },
    { bucket: "02:00", alerts: 4, incidents: 1 },
    { bucket: "04:00", alerts: 1, incidents: 0 },
    { bucket: "06:00", alerts: 3, incidents: 0 },
    { bucket: "08:00", alerts: 7, incidents: 1 },
    { bucket: "10:00", alerts: 12, incidents: 1 },
    { bucket: "12:00", alerts: 6, incidents: 1 },
    { bucket: "14:00", alerts: 5, incidents: 0 },
  ],
  incidents_by_severity: [
    { severity: "critical", count: 1 },
    { severity: "high", count: 2 },
    { severity: "medium", count: 1 },
    { severity: "low", count: 0 },
  ],
  correlation_ratio: { correlated: 17, uncorrelated: 6 },
  top_hosts: [
    { host: "ubuntu-server", alerts: 11 },
    { host: "win-workstation-02", alerts: 6 },
    { host: "web-node-01", alerts: 4 },
    { host: "db-node-01", alerts: 3 },
  ],
  top_source_ips: [
    { source_ip: "192.168.1.25", alerts: 8 },
    { source_ip: "192.168.1.31", alerts: 4 },
    { source_ip: "10.10.20.77", alerts: 3 },
    { source_ip: "192.168.1.18", alerts: 2 },
    { source_ip: "192.168.1.44", alerts: 1 },
  ],
  mitre_distribution: [
    { technique_id: "T1059", name: "Command and Scripting Interpreter", count: 3 },
    { technique_id: "T1110", name: "Brute Force", count: 2 },
    { technique_id: "T1078", name: "Valid Accounts", count: 2 },
    { technique_id: "T1053", name: "Scheduled Task/Job", count: 1 },
    { technique_id: "T1595", name: "Active Scanning", count: 1 },
  ],
};

export const demoAnalytics: AnalyticsMetrics = {
  alerts_per_day: [
    { day: "Aug 03", alerts: 18 },
    { day: "Aug 04", alerts: 24 },
    { day: "Aug 05", alerts: 15 },
    { day: "Aug 06", alerts: 31 },
    { day: "Aug 07", alerts: 27 },
    { day: "Aug 08", alerts: 21 },
    { day: "Aug 09", alerts: 23 },
  ],
  incidents_per_day: [
    { day: "Aug 03", incidents: 2 },
    { day: "Aug 04", incidents: 3 },
    { day: "Aug 05", incidents: 1 },
    { day: "Aug 06", incidents: 5 },
    { day: "Aug 07", incidents: 4 },
    { day: "Aug 08", incidents: 2 },
    { day: "Aug 09", incidents: 4 },
  ],
  severity_distribution: [
    { severity: "critical", count: 3 },
    { severity: "high", count: 8 },
    { severity: "medium", count: 7 },
    { severity: "low", count: 3 },
  ],
  correlation_rate: 0.74,
  false_positive_rate: null,
  triage_time_minutes: [
    { day: "Aug 05", minutes: 22 },
    { day: "Aug 06", minutes: 18 },
    { day: "Aug 07", minutes: 16 },
    { day: "Aug 08", minutes: 15 },
    { day: "Aug 09", minutes: 14 },
  ],
};

export const demoHealth: HealthResponse = {
  status: "degraded",
  environment: "LAB",
  demo_mode: true,
  components: [
    { key: "wazuh", name: "Wazuh API", role: "Security event collection and alert generation", state: "unknown", detail: "Reported by SentinelIQ backend — not reachable from the browser.", latency_ms: null },
    { key: "fastapi", name: "SentinelIQ FastAPI", role: "Ingestion, correlation, triage orchestration", state: "disconnected", detail: "No response from http://localhost:8000/api/health", latency_ms: null },
    { key: "postgres", name: "PostgreSQL", role: "Persists processed incidents and related data", state: "unknown", detail: "Reported by backend health endpoint.", latency_ms: null },
    { key: "xgboost", name: "XGBoost model", role: "Incident priority prediction", state: "unknown", detail: "Reported by backend health endpoint.", latency_ms: null },
    { key: "shap", name: "SHAP explainer", role: "Explains the XGBoost prediction", state: "unknown", detail: "Reported by backend health endpoint.", latency_ms: null },
    { key: "ollama", name: "Ollama (local LLM)", role: "Human-readable incident summary", state: "unknown", detail: "Reported by backend health endpoint.", latency_ms: null },
    { key: "frontend", name: "React frontend", role: "SOC analyst interface", state: "online", detail: "Rendering with demo dataset.", latency_ms: null },
  ],
  checked_at: t("10:40:00"),
};
